install.packages("magrittr")
install.packages("BBmisc")
install.packages("curl")
install.packages("dplyr")
install.packages("jsonlite")
install.packages("stringi")
install.packages("aws.dynamodb", repos = c(cloudyr = "http://cloudyr.github.io/drat", getOption("repos")))